# Use the official PostgreSQL image as a base
FROM postgres:16.3

# Install PostGIS
RUN apt-get update && apt-get install -y postgis postgresql-16-postgis-3

# Copy the initialization script
COPY init_postgis.sh /docker-entrypoint-initdb.d/
