@startuml

object "torino: City" as Torino {
name = "Torino"
}

object "athens: City" as Athens {
    name = "Athens"
}

object "cascais: City" as Cascais {
    name = "Cascais"
}

object "sofia: City" as Sofia {
    name = "Sofia"
}

object "grenoble: City" as Grenoble {
    name = "Grenoble-Alpes"
}

object "maribor: City" as Maribor {
    name = "Maribor"
}

object "ioannina: City" as Ioannina {
    name = "Ioannina"
}


object "differdange: City" as Differdange {
name = "Differdange"
}


object "kpiTemp_Differdange: KPI" as KPITemperature_Differdange {
    id_kpi = "temp001"
    name = "Average Temperature"
    category = "Environment"
    description = "Measures the average temperature of the city"
    provider = "WeatherService"
    calculationFrequency = "Daily"
    unitText = "Celsius"
    minThreshold = 15
    maxThreshold = 35
    hasCategoryLabel = false
}

object "kpiMoney_Differdange: KPI" as KPIMoney_Differdange {
    id_kpi = "money001"
    name = "Money Invested"
    category = "Environment"
    description = "Measures the money invested in green stuff"
    provider = "BankService"
    calculationFrequency = "Weekly"
    unitText = "Euros"
    minThreshold = 500
    maxThreshold = 2000
    hasCategoryLabel = false
}




Differdange --> KPITemperature_Differdange
Differdange --> KPIMoney_Differdange

object "tempValue1: KPIValue" as TempValue1 {
    kpiValue = 22
    timestamp = "2025-07-07 10:00:00"
    categoryLabel = "Good"
}

object "moneyValue1: KPIValue" as MoneyValue1 {
    kpiValue = 1200
    timestamp = "2025-07-07 10:00:00"
    categoryLabel = "Good"
}

KPITemperature_Differdange --> TempValue1
KPIMoney_Differdange --> MoneyValue1



object "kpiTrafficCongestion_Sofia: KPI" as KPITrafficCongestion_Sofia {
    id_kpi = "traffic001"
    name = "Traffic Congestion Level"
    category = "Transport"
    description = "Measures the level of traffic congestion"
    provider = "TransportDepartment"
    calculationFrequency = "Hourly"
    unitText = "Number of Cars"
    minThreshold = 10
    maxThreshold = 50
    hasCategoryLabel = false
}






Sofia --> KPITrafficCongestion_Sofia


object "kpiCollectedWaste_Cascais: KPI" as KPICollectedWaste_Cascais {
    id_kpi = "waste001"
    name = "Collected Textile Waste in Ton"
    category = "Waste"
    description = "Total textile waste collected in Cascais"
    provider = "WasteDepartment"
    calculationFrequency = "Weekly"
    unitText = "Tons"
    minThreshold = 5
    maxThreshold = 15
    hasCategoryLabel = false
}


object "kpiCSecondHandCustomers_Cascais: KPI" as KPISecondHandCustomers_Cascais {
    id_kpi = "waste002"
    name = "Customers in second hand shops"
    category = "Waste"
    description = "Daily number of customers in second hand shops"
    provider = "Shops"
    calculationFrequency = "Daily"
    unitText = "Number of people"
    minThreshold = 500
    maxThreshold = 1500
    hasCategoryLabel = true
}



object "kpiTotalRenewableEnergy_Differdange: KPI" as KPITotalRenewableEnergy_Differdange {
    id_kpi = "energy001"
    name = "Percentage of renewable energy in Differdange"
    category = "Energy"
    description = "Percentage of renewable energy in Differdange based on total amount of energy"
    provider = "Solution Provider"
    calculationFrequency = "Monthly"
    unitText = "Percentage"
    minThreshold = 15
    maxThreshold = 25
    hasCategoryLabel = false
}


object "kpiNumberHouseholdRenewableEnergy_Differdange: KPI" as KPINumberHouseholdRenewableEnergy_Differdange {
    id_kpi = "energy002"
    name = "Household with renewable energy"
    category = "Energy"
    description = "Number of households producing any kind of renewable energy"
    provider = "Citizens"
    calculationFrequency = "Monthly"
    unitText = "Number"
    minThreshold = 300
    maxThreshold = 700
    hasCategoryLabel = false
}


object "kpiPeakSolarEnergy_Differdange: KPI" as KPIPeakSolarEnergy_Differdange {
    id_kpi = "energy003"
    name = "Peak solar energy"
    category = "Energy"
    description = "Peak solar energy in Differdange"
    provider = "Differdange"
    calculationFrequency = "Monthly"
    unitText = "KW peak"
    minThreshold = 800
    maxThreshold = 1200
    hasCategoryLabel = false
}

Differdange --> KPITotalRenewableEnergy_Differdange
Differdange --> KPINumberHouseholdRenewableEnergy_Differdange
Differdange --> KPIPeakSolarEnergy_Differdange



Cascais --> KPICollectedWaste_Cascais


Cascais --> KPISecondHandCustomers_Cascais

object "kpiInformedCitizens: KPI" as KPIInformedCitizens_Torino {
    id_kpi = "participants_001"
    name = "Citizens informed through Re4Circular"
    category = "Waste"
    description = "Citizens informed through Re4Circular"
    provider = "Re4Circular"
    calculationFrequency = "Monthly"
    unitText = "Number of people"
    minThreshold = 800
    maxThreshold = 1200
    hasCategoryLabel = false
}

object "kpiInvolvedCitizens: KPI" as KPIInvolvedCitizens_Torino {
    id_kpi = "participants_002"
    name = "Citizens active on Re4Circular"
    category = "Waste"
    description = "Citizens active on Re4Circular"
    provider = "Re4Circular"
    calculationFrequency = "Monthly"
    unitText = "Number of people"
    minThreshold = 400
    maxThreshold = 600
    hasCategoryLabel = false
}


object "kpiInformedBusinesses: KPI" as KPIInformedBusinesses_Torino {
    id_kpi = "participants_003"
    name = "Businesses informed through Re4Circular"
    category = "Waste"
    description = "Businesses informed through Re4Circular"
    provider = "Re4Circular"
    calculationFrequency = "Monthly"
    unitText = "Number of businesses"
    minThreshold = 40
    maxThreshold = 60
    hasCategoryLabel = false
}

object "kpiInvolvedBusinesses: KPI" as KPIInvolvedBusinesses_Torino {
    id_kpi = "participants_004"
    name = "Businesses active on Re4Circular"
    category = "Waste"
    description = "Businesses active on Re4Circular"
    provider = "Re4Circular"
    calculationFrequency = "Monthly"
    unitText = "Number of businesses"
    minThreshold = 15
    maxThreshold = 25
    hasCategoryLabel = false
}

object "kpiReuseBusinesses: KPI" as KPIReuseBusinesses_Torino {
    id_kpi = "participants_005"
    name = "Businesses re-using textiles through Re4Circular"
    category = "Waste"
    description = "Businesses re-using textiles through Re4Circular"
    provider = "Re4Circular"
    calculationFrequency = "Monthly"
    unitText = "Number of businesses"
    minThreshold = 8
    maxThreshold = 12
    hasCategoryLabel = false
}

object "kpiWasteAvoided: KPI" as KPIWasteAvoided_Torino {
    id_kpi = "waste_001"
    name = "Waste avoided through Re4Circular"
    category = "Waste"
    description = "Waste avoided through Re4Circular (collecting material before it becomes waste)"
    provider = "Re4Circular"
    calculationFrequency = "Monthly"
    unitText = "Tons"
    minThreshold = 8
    maxThreshold = 12
    hasCategoryLabel = false
}

object "kpiCo2Avoided: KPI" as KPICo2Avoided_Torino {
    id_kpi = "co2_001"
    name = "Co2 avoided through collection of waste through Re4Circular"
    category = "Waste"
    description = "Co2 avoided through collection of waste through Re4Circular"
    provider = "DKSR"
    calculationFrequency = "Monthly"
    unitText = "Tons"
    minThreshold = 2
    maxThreshold = 8
    hasCategoryLabel = false
}

object "kpiWasteSorted: KPI" as KPIWasteSorted_Torino {
    id_kpi = "waste_006"
    name = "Amount of correctly sorted waste in bins using ReLearn sensors"
    category = "Waste"
    description = "Amount of correctly sorted waste in bins using ReLearn sensors"
    provider = "ReLearn"
    calculationFrequency = "Monthly"
    unitText = "Kg"
    minThreshold = 800
    maxThreshold = 1200
    hasCategoryLabel = false
}


object "kpiCollectedWaste: KPI" as KPICollectedWaste_Torino {
    id_kpi = "waste_007"
    name = "Amount of collected textile waste"
    category = "Waste"
    description = "Amount of collected textile waste"
    provider = "ReLearn"
    calculationFrequency = "Monthly"
    unitText = "Kg"
    minThreshold = 5000
    maxThreshold = 7000
    hasCategoryLabel = false
}




object "kpiTextileWastePerPerson: KPI" as KPITextileWastePerPerson_Torino {
    id_kpi = "waste_010"
    name = "Amount of yearly textile waste per person"
    category = "Waste"
    description = "Amount of yearly textile waste per person"
    provider = "City"
    calculationFrequency = "Yearly"
    unitText = "Kg"
    minThreshold = 10
    maxThreshold = 30
    hasCategoryLabel = false
}

object "kpiHouseholdInvolvedThreeBagCollection: KPI" as KPIHouseholds_Torino {
    id_kpi = "participants_006"
    name = "Households participating in the three bags collection"
    category = "Waste"
    description = "Households participating in the three bags collection"
    provider = "Torino"
    calculationFrequency = "Monthly"
    unitText = "Households"
    minThreshold = 80
    maxThreshold = 120
    hasCategoryLabel = false
}

object "kpiCollectedClothes: KPI" as KPICollectedClothes_Torino {
    id_kpi = "waste_011"
    name = "Amount of collected textile clothes"
    category = "Waste"
    description = "Amount of collected textile clothes"
    provider = "City of Torino"
    calculationFrequency = "Monthly"
    unitText = "Kg"
    minThreshold = 5500
    maxThreshold = 6500
}




object "kpiCollectedTextileWaste: KPI" as KPICollectedTextileWaste_Torino {
    id_kpi = "waste_012"
    name = "Amount of other types of textiles collected"
    category = "Waste"
    description = "Amount of other types of textiles collected"
    provider = "City of Torino"
    calculationFrequency = "Monthly"
    unitText = "Kg"
    minThreshold = 4500
    maxThreshold = 5500
}

object "kpiDiscardedWaste: KPI" as KPIDiscardedTextileWaste_Torino {
    id_kpi = "waste_013"
    name = "Amount of textile waste discarded from the differentiated share"
    category = "Waste"
    description = "Amount of textile waste discarded from the differentiated share"
    provider = "City of Torino"
    calculationFrequency = "Monthly"
    unitText = "Kg"
    minThreshold = 40
    maxThreshold = 60
}

object "kpiCollectedTextileWasteEcoIsole: KPI" as KPICollectedTextileWasteEcoIsole_Torino {
    id_kpi = "waste_014"
    name = "Amount of textile left in the indifferentiated waste (Eco-Isole)"
    category = "Waste"
    description = "Amount of textile left in the indifferentiated waste (Eco-Isole)"
    provider = "City of Torino"
    calculationFrequency = "Monthly"
    unitText = "Kg"
    minThreshold = 2800
    maxThreshold = 3200
}


object "kpiCollectedClothes2: KPI" as KPICollectedClothes_Torino2 {
    id_kpi = "waste_015"
    name = "Amount of collected textile clothes"
    category = "Waste"
    description = "Amount of collected textile clothes"
    provider = "City of Torino"
    calculationFrequency = "Monthly"
    unitText = "Kg"
    minThreshold = 90
    maxThreshold = 110
}

Torino --> KPICollectedClothes_Torino
Torino --> KPICollectedTextileWaste_Torino
Torino --> KPICollectedTextileWasteEcoIsole_Torino
Torino --> KPIInformedCitizens_Torino
Torino --> KPIDiscardedTextileWaste_Torino
Torino --> KPIInvolvedCitizens_Torino
Torino --> KPIInformedBusinesses_Torino
Torino --> KPIInvolvedBusinesses_Torino
Torino --> KPIReuseBusinesses_Torino
Torino --> KPIWasteAvoided_Torino
Torino --> KPICo2Avoided_Torino
Torino --> KPIWasteSorted_Torino
Torino --> KPICollectedWaste_Torino
Torino --> KPITextileWastePerPerson_Torino
Torino --> KPIHouseholds_Torino

Torino --> KPICollectedClothes_Torino2



@enduml
